spring:
  application:
    name: centralized-auth-gateway
    
server:
  port: 8082
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
    instance:
      hostname: localhost